In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

인덱싱

numpy 배열의 각 요소는 axis 인덱스 배열로 참조할 수 있다.  
1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스, 3차원 배열은 3개의 인덱스로 요소를 참조할 수 있다.  
인덱싱 작업시 [행][열]과 같이 인덱스를 지정하거나 [행, 열]과 같이 인덱스를 지정할 수 있다.

In [2]:
# 1차원 배열 요소 참조 및 변경
a = np.arange(24) # 1차원 배열
print(a)
print(a[5])
a[5] = 10000
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5
[    0     1     2     3     4 10000     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23]


In [3]:
# 2차원 배열 요소 참조 및 변경
b = np.arange(24).reshape(4, 6) # 2차원 배열
print(b)
print(b[1][2])
b[1, 2] = 10000
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
8
[[    0     1     2     3     4     5]
 [    6     7 10000     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]


In [4]:
# 3차원 배열 요소 참조 및 변경
c = np.arange(24).reshape(2, 4, 3) # 3차원 배열
print(c)
print(c[1][3][2])
c[1, 3, 2] = 10000
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
23
[[[    0     1     2]
  [    3     4     5]
  [    6     7     8]
  [    9    10    11]]

 [[   12    13    14]
  [   15    16    17]
  [   18    19    20]
  [   21    22 10000]]]


슬라이싱

In [5]:
print(a)
print(a[2:6])

[    0     1     2     3     4 10000     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23]
[    2     3     4 10000]


<img src="./numpyImage06.jpg" align="left" width="700"/>

In [6]:
print(b)
print('=' * 80)
# 열을 생략하면 전체 열을 의미하므로 행 단위 슬라이싱을 할 수 있다.
print(b[1:3]) # b[1:3, :]와 같은 표현이다.
print('=' * 80)
# 열 단위 슬라이싱을 하려면 행 위치에 반드시 ':'을 적어야 한다. ':'은 전체 행을 의미한다.
print(b[:, 1:5])
print('=' * 80)
# 인덱싱은 [행][열] 방식이나 [행, 열] 방식을 모두 사용할 수 있지만 슬라이싱은 [행, 열] 방식만
# 사용할 수 있다.
# b[1:3][1:5] 방식으로 슬라이싱 하면 b[1:3]로 슬라이싱한 결과에서 [1:5]로 슬라이싱 한다.
print(b[1:3][1:5])
print('=' * 80)
print(b[1:3, 1:5])

[[    0     1     2     3     4     5]
 [    6     7 10000     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]
[[    6     7 10000     9    10    11]
 [   12    13    14    15    16    17]]
[[    1     2     3     4]
 [    7 10000     9    10]
 [   13    14    15    16]
 [   19    20    21    22]]
[[12 13 14 15 16 17]]
[[    7 10000     9    10]
 [   13    14    15    16]]


<img src="./numpyImage07.jpg" align="left" width="700"/>

In [7]:
# 음수 인덱싱을 이용한 범위 설정
# 음수 인덱스는 지정한 axis의 마지막 요소부터 반대 방향의 인덱스이고 -1은 마지막 요소의 인덱스를 의미한다.
print(b[1:3, 1:5])
print('=' * 80)
print(b[1:-1, 1:-1])

[[    7 10000     9    10]
 [   13    14    15    16]]
[[    7 10000     9    10]
 [   13    14    15    16]]


In [8]:
# 슬라이싱을 이용한 데이터 수정
print(b)
print('=' * 80)
slide_arr = b[1:3, 1:5] # 얕은 복사
print(slide_arr)
print('=' * 80)
slide_arr[:, 1:3] = 99999
print(slide_arr)
print('=' * 80)
print(b)

[[    0     1     2     3     4     5]
 [    6     7 10000     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]
[[    7 10000     9    10]
 [   13    14    15    16]]
[[    7 99999 99999    10]
 [   13 99999 99999    16]]
[[    0     1     2     3     4     5]
 [    6     7 99999 99999    10    11]
 [   12    13 99999 99999    16    17]
 [   18    19    20    21    22    23]]


불린 인덱싱

numpy의 불린 인덱싱은 배열의 각 요소의 선택 여부를 True, False로 지정하는 방식이다. => True가 선택된다.

In [9]:
a = np.arange(24).reshape(4, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


a 배열에서 요소의 값이 짝수인 요소의 전체 합계

In [10]:
# 브로드캐스팅 기능을 이용해서 배열 요소 중에서 짝수인 요소를 확인한다.
even_arr1 = a % 2 # 브로드캐스팅
print(even_arr1)
even_arr2 = even_arr1 == 0 # 브로드캐스팅
print(even_arr2)
print('=' * 80)
even_arr = a % 2 == 0
print(even_arr)

[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]


In [11]:
# 불린 인덱싱은 브로드캐스팅 결과가 True인 요소들만 추출한다.
print(a[even_arr])
print(a[a % 2 == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [12]:
print(a.sum())
print(np.sum(a))
print(a[a % 2 == 0].sum())
print(np.sum(a[a % 2 == 0]))
print(a[a % 2 == 1].sum())
print(np.sum(a[a % 2 != 0]))

276
276
132
132
144
144


불린 인덱싱 응용

데이터 파일 => 2014년 시애틀 강수량 데이터 => ./data/Seattle2014.csv

In [13]:
import pandas as pd

In [14]:
# 2014년 1월 시애틀의 평균 강수량?
# pandas의 read_csv() 메소드는 csv 파일을 읽어서 데이터프레임으로 리턴한다.
seattle_df = pd.read_csv('./data/Seattle2014.csv')
print(type(seattle_df))
seattle_df

<class 'pandas.core.frame.DataFrame'>


STATION                                STATION_NAME      DATE  \
0    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   
..                 ...                                         ...       ...   
360  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141227   
361  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141228   
362  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141229   
363  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141230   
364  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141231   

     PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0       0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1      41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2      15     0     0    89    28    26    30    50    63    72     1 -9999   
3       0     0     0    78     6    27    40    40    45    58     1 -9999   
4       0     0     0    83    -5    37    10    10    67    76 -9999 -9999   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
360    33     0     0    94    44    49   210   210   112   161     1 -9999   
361    41     0     0    67    28    18    50    30    58    72     1 -9999   
362     0     0     0    61     6    43   350   350    76   103     1 -9999   
363     0     0     0    33   -21    36    90    70    63    76 -9999 -9999   
364     0     0     0    33   -27    30    30 -9999    58 -9999 -9999 -9999   

     WT02  WT03  
0   -9999 -9999  
1   -9999 -9999  
2   -9999 -9999  
3   -9999 -9999  
4   -9999 -9999  
..    ...   ...  
360 -9999 -9999  
361 -9999 -9999  
362 -9999 -9999  
363 -9999 -9999  
364 -9999 -9999  

[365 rows x 17 columns]

In [15]:
# 2014년 시애틀 강수량 데이터의 강수량 열(시리즈) PRCP의 데이터만 추출한다.
# 데이터프레임의 특정 시리즈 추출하는 방법은 아래와 같이 3가지가 있다.
# rain = seattle_df.get('PRCP') # 데이터프레임이름.get('시리즈이름')
# rain = seattle_df['PRCP'] # 데이터프레임이름['시리즈이름']
rain = seattle_df.PRCP # 데이터프레임이름.시리즈이름
print(type(rain))
print(rain)

<class 'pandas.core.series.Series'>
0       0
1      41
2      15
3       0
4       0
       ..
360    33
361    41
362     0
363     0
364     0
Name: PRCP, Length: 365, dtype: int64


In [17]:
# 시리즈에서 인덱스만 얻어오려면 index 속성을 사용하고 데이터만 얻어오려면 values 속성을 사용한다.
# print(list(rain.index))
print(type(rain.values)) # 시리즈의 데이터는 numpy 배열 형태로 얻어온다.
print(len(rain.values))
rain_arr = rain.values
print(rain_arr[:40])

<class 'numpy.ndarray'>
365
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23  20   0   0   0   0
   0   0  51   5]


In [18]:
days_arr = np.arange(365) # 날짜 배열
print(days_arr[:40])
# 1월의 날 수 만큼 불린 인덱스를 생성한다.
jan = days_arr < 31
print(jan[:40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False]


In [19]:
# 불린 인덱싱을 이용해서 1월의 강수량만 추출한다.
rain_jan = rain_arr[jan]
print(len(rain_jan))
print(rain_jan)

31
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


In [22]:
print('1월 강수량 합계: {}'.format(np.sum(rain_jan)))
print('1월 강수량 평균: {:.1f}'.format(np.mean(rain_jan)))

1월 강수량 합계: 940
1월 강수량 평균: 30.3
