In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


<img src="./multilayer_perceptron1.png" align="left" width="1600"/>

<img src="./multilayer_perceptron2.png" align="left" width="1600"/>

<img src="./multilayer_perceptron3.png" align="left" width="1600"/>

<img src="./multilayer_perceptron4.png" align="left" width="1600"/>

XOR 연산은 입력 데이터를 X라고 할 경우 [[0, 0], [0, 1], [1, 0], [1, 1]]과 같은 경우의 수가 있다.  
총 4개의 데이터가 각각 2개의 특성을 가지고 있으므로 X는 [4, 2]의 형태로 정의할 수 있다.  
입력값에 따른 출력값 Y는 [[0], [1], [1], [0]]이므로 Y는 [4, 1]의 형태로 정의할 수 있다.

In [2]:
X = tf.placeholder(dtype=tf.float32, shape=[4, 2]) # 학습 데이터
Y = tf.placeholder(dtype=tf.float32, shape=[4, 1]) # 레이블

1번째 히든 레이어에서 2개의 입력(X)과 1개의 편향값(B1)을 받아서 2개의 시그모이드 출력(Z)을 2번째 히든 레이어로 전달한다.

In [3]:
# 2개의 입력을 받는 2개의 뉴런을 사용하기 위해서 가중치를 [건당 데이터 개수, 뉴런의 개수] 만큼의 난수를 만든다.
W1 = tf.Variable(tf.random_normal([2, 2]))
# 각 뉴런은 1개의 편향값을 가진다.
# zeros() 메소드는 모든 원소의 값이 0인 텐서(2차원 이상의 행렬)를 생성한다.
B1 = tf.Variable(tf.zeros([2]))
# 시그모이드 함수를 이용해서 1번째 히든 레이어의 출력을 리턴한다.
Z = tf.sigmoid(tf.matmul(X, W1) + B1)

In [4]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(W1))
print(sess.run(B1))
x_train = [[0, 0], [0, 1], [1, 0], [1, 1]]
print(sess.run(Z, feed_dict={X: x_train}))
sess.close()

[[ 0.9895296  -1.1099348 ]
 [-0.86128294  0.5428039 ]]
[0. 0.]
[[0.5        0.5       ]
 [0.29707137 0.6324644 ]
 [0.728995   0.24788305]
 [0.5320178  0.3618991 ]]


2번째 히든 레이어에서 1번째 히든 레이어의 출력값(Z)와 편향값(B2)을 받아서 1개의 시그모이드를 출력(Y_hat)한다.

In [5]:
# 2개의 Z(z1, z2)를 입력값으로 받는 1개의 뉴런을 만든다.
W2 = tf.Variable(tf.random_normal([2, 1]))
B2 = tf.Variable(tf.zeros([1]))
Y_hat = tf.sigmoid(tf.matmul(Z, W2) + B2)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(W2))
print(sess.run(B2))
print(sess.run(Y_hat, feed_dict={X: x_train}))
sess.close()

[[ 0.27934355]
 [-0.62454134]]
[0.]
[[0.4569571 ]
 [0.46375203]
 [0.36846575]
 [0.370741  ]]


손실 함수로 크로스 엔트로피를 사용하고 경사 하강법으로 모델의 매개 변수(가중치, 편향)를 최적화 한다.

In [7]:
# 크로스 엔트로피
loss = tf.reduce_mean(
    -1 * (Y * tf.log(Y_hat) + (1.0 - Y) * tf.log(1.0 - Y_hat))
)
# 경사 하강법
train_step = tf.train.GradientDescentOptimizer(0.05).minimize(loss)
# 모델을 학습하기 위한 학습 데이터와 레이블을 만든다.
x_train = [[0, 0], [0, 1], [1, 0], [1, 1]]
y_train = [[0], [1], [1], [0]]

학습 시킨다.

In [8]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('학습 데이터: {}'.format(x_train))
print('=' * 80)

for epoch in range(40001):
    sess.run(train_step, feed_dict={X: x_train, Y: y_train})
    if epoch % 5000 == 0:
        print('epoch: {}'.format(epoch))
        print('output\n', sess.run(Y_hat, feed_dict={X: x_train}), sep='')

학습 데이터: [[0, 0], [0, 1], [1, 0], [1, 1]]
epoch: 0
output
[[0.43812203]
 [0.43003622]
 [0.4391236 ]
 [0.43131456]]
epoch: 5000
output
[[0.5022958 ]
 [0.49951538]
 [0.500105  ]
 [0.49734202]]
epoch: 10000
output
[[0.50328535]
 [0.50272727]
 [0.49701518]
 [0.4962989 ]]
epoch: 15000
output
[[0.5043876 ]
 [0.507397  ]
 [0.4922032 ]
 [0.49438164]]
epoch: 20000
output
[[0.5019337 ]
 [0.5420312 ]
 [0.46060124]
 [0.48030305]]
epoch: 25000
output
[[0.36855686]
 [0.85175943]
 [0.3671465 ]
 [0.35783115]]
epoch: 30000
output
[[0.08811929]
 [0.8993576 ]
 [0.88267654]
 [0.07513106]]
epoch: 35000
output
[[0.03865754]
 [0.95186335]
 [0.94927686]
 [0.03370442]]
epoch: 40000
output
[[0.02426036]
 [0.96913016]
 [0.96812165]
 [0.02130367]]
